# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.3
loader_version=0.19.5
loom_version=1.18-SNAPSHOT

# Mod Properties
version=1.2.1-banan+26.3
group=be.florens.svcgroupplayernames

# Dependencies
fabric_api_version=0.161.0+26.3
voicechat_version=fabric-2.6.24+26.3
cloth_config_version=26.3.159
modmenu_version=21.0.0
styled_nicknames_version=1.14.0+26.3
